[package]
name = "flash_card"
version = "0.1.0"
author = ["Jinof <Jinof@foxmail.com>"]
editon = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]